### ISSUE TITLE
Support For SqlLite

### ISSUE THREAD

**Issue by jonrobinson** [marktopper/doctrine-dbal-timestamp-type#3]

**Comment by Quix0r** [comment]
Should be trivial to add, just replace `if (in_array($name, ['mysql'])) {` with `if (in_array($name, ['mysql', 'sqlite3'])) {` in `MarkTopper\DoctrineDBALTimestampType\TimestampType` class. Well, I mean, create a PR that does this.

**Comment by Quix0r** [comment]
Still I found this static. Isn't there a vendor-independent query for supported types? Or use some meta-data information class/method from PHP?

**Comment by marktopper** [comment]
Closed by #4.

Released as `v1.0.2`.
